Repository RedHatQE/openshift-cli-installer, pull requests merged in 2023-09, with the labels that each got.

#117 Use cluster ocm client and add info to cluster data
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/aws_ipi_clusters.py
  openshift_cli_installer/libs/osd_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/utils/const.py
  openshift_cli_installer/utils/helpers.py
  poetry.lock
  pyproject.toml
Labels: size/XXL, verified, branch-main, can-be-merged, ApprovedBy-myakove

#133 Check existing rosa/hypershift clusters in both envs
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/rosa_clusters.py
Labels: verified, branch-main, can-be-merged, ApprovedBy-myakove, size/m

#137 AWS OSD - dump cluster auth to files
  openshift_cli_installer/libs/osd_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
  openshift_cli_installer/utils/helpers.py
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-myakove

#141 Update cluster object based on changes in OCM wrapper
  openshift_cli_installer/libs/osd_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
  openshift_cli_installer/utils/helpers.py
Labels: verified, branch-main, size/S

#135 use cluster names to check existing clusters
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/osd_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
  openshift_cli_installer/utils/helpers.py
Labels: verified, branch-main, can-be-merged, ApprovedBy-myakove, size/m

#145 Set default timeout to 60m and restructure code
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/managed_clusters/__init__.py
  openshift_cli_installer/libs/managed_clusters/helpers.py
  openshift_cli_installer/libs/managed_clusters/osd_clusters.py
  openshift_cli_installer/libs/managed_clusters/rosa_clusters.py
  openshift_cli_installer/libs/unmanaged_clusters/__init__.py
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/const.py
  openshift_cli_installer/utils/general.py
Labels: verified, branch-main, size/XL, can-be-merged, ApprovedBy-myakove

#147 Support user config to create clusters from YAML file
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/managed_clusters/osd_clusters.py
  openshift_cli_installer/libs/managed_clusters/rosa_clusters.py
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/manifests/clusters.example.yaml
  openshift_cli_installer/utils/clusters.py
  poetry.lock
  pyproject.toml
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-rnetser

#156 Add s3 bucket to all clusters
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/managed_clusters/osd_clusters.py
  openshift_cli_installer/libs/managed_clusters/rosa_clusters.py
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/general.py
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-myakove

#163 Add Makefile
  Makefile
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-rnetser

#162 Add color to success logs
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/managed_clusters/osd_clusters.py
  openshift_cli_installer/libs/managed_clusters/rosa_clusters.py
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/const.py
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-myakove

#168 HCP - add default ocm-env
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-myakove

#171 Add Advanced cluster management (cm) cli to the image
  Dockerfile
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-rnetser

#174 Add support to install ACM on cluster and attach clusters to ACM hub
  Dockerfile
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/managed_clusters/acm_clusters.py
  openshift_cli_installer/libs/managed_clusters/osd_clusters.py
  openshift_cli_installer/libs/managed_clusters/rosa_clusters.py
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/manifests/clusters.example.yaml
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/const.py
Labels: size/XXL, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#179 Change id_rsa permissions to reabable
  Dockerfile
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove

#181 Exit after deletion of all clusters or from s3 bucket
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/utils/cli_utils.py
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-myakove

#183 Add GCP OSD cluster installation
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/managed_clusters/helpers.py
  openshift_cli_installer/libs/managed_clusters/osd_clusters.py
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/manifests/clusters.example.yaml
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/const.py
  openshift_cli_installer/utils/gcp.py
  poetry.lock
  pyproject.toml
Labels: size/XXL, verified, branch-main, can-be-merged, ApprovedBy-myakove

#177 Correct an example in README
  README.md
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-rnetser

#188 Fix `gcp-service-account-file` kwarg name
  openshift_cli_installer/cli.py
Labels: verified, branch-main, size/XS

#192 Fix get max version
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/utils/cluster_versions.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-rnetser

#190 Clusters region check only on create and fix gcp SA file check
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/managed_clusters/helpers.py
  openshift_cli_installer/manifests/clusters.example.yaml
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-myakove, ApprovedBy-oharan2

#196 Fix error on timeout when creating AWS IPI cluster with ACM
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/managed_clusters/helpers.py
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, can-be-merged, size/m, ApprovedBy-rnetser

#199 destroy_clusters_from_data_dict: use ThreadPoolExecutor if parallel
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/destroy_clusters.py
Labels: verified, branch-main, can-be-merged, size/m, ApprovedBy-rnetser

#201 get_files_from_s3_bucket: use ThreadPoolExecutor()
  openshift_cli_installer/libs/destroy_clusters.py
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-rnetser

#203 Split AWS install/uninstall function
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/utils/cli_utils.py
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-myakove, CommentedBy-rnetser

#207 add chetna14manku to owner file
  OWNERS
Labels: branch-main, size/XS, ApprovedBy-rnetser
