Repository RedHatQE/openshift-cli-installer, pull requests merged in 2023-12, with the labels that each got.

#330 S3 bucket path UUID from user
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/aws_ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/scripts/openshift-cli-installer-build-command.py
Labels: verified, branch-main, size/S

#334 Set either `s3-bucket-path-uuid` os shortuuid
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/aws_ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, can-be-merged, size/m, approved-myakove

#337 Add `s3_bucket_name` and `s3_bucket_path` to `cluster_info`
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove, commented-myakove, commented-rnetser

#340 Build command tests
  openshift_cli_installer/scripts/openshift-cli-installer-build-command.py
  openshift_cli_installer/tests/test_build_command_script.py
Labels: verified, branch-main, can-be-merged, size/S, needs-rebase, approved-rnetser
