Repository RedHatQE/openshift-cli-installer, pull requests merged in 2023-07, with the labels that each got.

#4 support rosa and hypershift clusters
  Dockerfile
  app/cli.py
  app/libs/__init__.py
  app/libs/aws_ipi_clusters.py
  app/libs/rosa_clusters.py
  app/manifests/setup-vpc.tf
  app/utils/__init__.py
  app/utils/click_dict_type.py
  app/utils/const.py
  app/utils/helpers.py
  poetry.lock
  pyproject.toml
Labels: size/XXL, approved-by-rnetser, verified, branch-main, can-be-merged

#10 expiration_time: can be any time, not just hours
  app/libs/rosa_clusters.py
Labels: approved-by-rnetser, verified, branch-main, size/XS, can-be-merged

#12 Update README
  README.md
  app/cli.py
Labels: verified, approved-by-oharan2, approved-by-omrirh, size/L, branch-main, approved-by-myakove, can-be-merged

#15 Fix poetry path install in dockerfile
  Dockerfile
Labels: approved-by-rnetser, verified, branch-main, size/XS, can-be-merged

#17 Add support for vpc network config
  README.md
  app/libs/rosa_clusters.py
  app/manifests/setup-vpc.tf
Labels: verified, branch-main, approved-by-myakove, can-be-merged, size/S

#19 Get cluster CIDR from cli
  app/libs/rosa_clusters.py
Labels: verified, approved-by-omrirh, branch-main, size/XS, approved-by-myakove, can-be-merged

#21 Upload to s3 any cluster platform
  README.md
  app/cli.py
  app/libs/aws_ipi_clusters.py
  app/libs/rosa_clusters.py
  app/utils/helpers.py
Labels: approved-by-rnetser, verified, size/L, branch-main, can-be-merged

#25 Add client and region to check_existing_clusters
  app/cli.py
Labels: verified, branch-main, size/XS, approved-by-myakove, can-be-merged

#27 Check cluster duplicate names only in create
  app/cli.py
Labels: verified, approved-by-omrirh, branch-main, size/XS, approved-by-myakove, can-be-merged

#29 Generate ssh-key in workdir and support get it from cli
  Dockerfile
  README.md
  app/cli.py
  app/libs/aws_ipi_clusters.py
Labels: approved-by-rnetser, verified, branch-main, can-be-merged, size/S

#31 update poetry
  poetry.lock
Labels: size/XXL, verified, branch-main, approved-by-myakove, can-be-merged

#33 update poetry
  poetry.lock
Labels: approved-by-rnetser, verified, size/L, branch-main, can-be-merged

#35 update rosa-python-client
  poetry.lock
Labels: verified, size/L, branch-main, approved-by-myakove, can-be-merged

#37 Poetry update rosa-python-client
  poetry.lock
Labels: approved-by-rnetser, verified, size/L, branch-main

#39 Update rosa-python-client version
  poetry.lock
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-myakove

#41 Raise if fail to download ocp installer
  app/libs/aws_ipi_clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove

#45 Cluster dicts - work on relevant platform dict
  app/cli.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove, lgtm, ApprovedBy-oharan2, CommentedBy-rnetser

#43 aws clusters - remove leftovers on installation failure
  app/libs/aws_ipi_clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove, ApprovedBy-oharan2, CommentedBy-rnetser
