Repository RedHatQE/openshift-cli-installer, pull requests merged in 2023-08, with the labels that each got.

#61 increase wait_for_osd_cluster_ready_job timeout
  app/libs/rosa_clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove

#68 cluster_data.yaml - add info to support openshift ci and delete hypershift oidc
  app/libs/aws_ipi_clusters.py
  app/libs/rosa_clusters.py
  app/utils/helpers.py
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-myakove

#58 Add option to uninstall all clusters
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/aws_ipi_clusters.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
  openshift_cli_installer/utils/const.py
  openshift_cli_installer/utils/helpers.py
Labels: verified, branch-main, size/XL, can-be-merged, ApprovedBy-myakove

#72 update s3 obj name and dump to file only during cluster create
  openshift_cli_installer/libs/aws_ipi_clusters.py
Labels: branch-main, size/S, ApprovedBy-myakove

#74 Add color to error logs
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/aws_ipi_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-myakove

#76 Delete Hypershift resources on clusetr creation failures
  openshift_cli_installer/libs/rosa_clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove, ApprovedBy-omrirh

#82 Support versions
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/aws_ipi_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
  openshift_cli_installer/tests/__init__.py
  openshift_cli_installer/tests/all_aws_versions.json
  openshift_cli_installer/tests/all_rosa_versions.py
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/utils/cluster_versions.py
  poetry.lock
  pyproject.toml
  tox.ini
Labels: size/XXL, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#87 Add release to pyproject
  .release-it.json
  VERSION
  poetry.lock
  pyproject.toml
Labels: size/XXL, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#90 Add command name to click command
  openshift_cli_installer/cli.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-rnetser

#92 Check if ssh-key-file is missing only if cluster is AWS IPI
  openshift_cli_installer/cli.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-rnetser

#94 Include manifests folder in release pkg
  openshift_cli_installer/libs/aws_ipi_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
  pyproject.toml
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-rnetser

#96 Fix manifests path for VPC
  openshift_cli_installer/libs/aws_ipi_clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-rnetser

#98 Fix manifest path for run from container
  openshift_cli_installer/libs/aws_ipi_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
  openshift_cli_installer/utils/helpers.py
Labels: verified, branch-main, can-be-merged, size/m, ApprovedBy-rnetser

#101 update cluster binary path selection
  openshift_cli_installer/libs/aws_ipi_clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove

#103 Remove redundant raise
  openshift_cli_installer/libs/aws_ipi_clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove

#106 Docker config and pull secret - unify for AWS pull secret
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/aws_ipi_clusters.py
  scripts/code_check/__init__.py
  scripts/code_check/unused_code.py
  tox.ini
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-myakove

#112 Aws osd cluster
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/osd_clusters.py
  openshift_cli_installer/libs/rosa_clusters.py
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/const.py
  openshift_cli_installer/utils/helpers.py
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-rnetser
