Repository RedHatQE/openshift-cli-installer, pull requests merged in 2023-11, with the labels that each got.

#281 OSD clusters - add channel group to version if not `stable` channel
  openshift_cli_installer/libs/clusters/osd_cluster.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove

#279 Add cluster_id to non-managed clusters
  openshift_cli_installer/libs/clusters/ocp_cluster.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-oharan2, approved-omrirh, approved-myakove

#283 Add cluster display_name to yaml file
  openshift_cli_installer/libs/clusters/ocp_cluster.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove

#285 Update OWNERS to add reviewer
  OWNERS
Labels: verified, branch-main, size/XS, can-be-merged, approved-rnetser

#286 Orgnize cluster parameters and add cluster_info attribute
  .pre-commit-config.yaml
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/aws_ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocm_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/ocp_clusters.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/manifests/clusters.example.yaml
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/general.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-omrirh, approved-myakove

#288 Remove broken `pycln` check and add ruff
  .flake8
  .pre-commit-config.yaml
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/aws_ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocm_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/ocp_clusters.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/tests/test_user_input.py
  openshift_cli_installer/tests/utils.py
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/const.py
  openshift_cli_installer/utils/general.py
  poetry.lock
  pyproject.toml
  scripts/code_check/unused_code.py
Labels: size/XXL, verified, branch-main, can-be-merged, has-conflicts, approved-rnetser

#292 Fix ROSA and logs
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/aws_ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/ocp_clusters.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, size/m

#295 pre-commit: remove FCN check
  .flake8
  .pre-commit-config.yaml
Labels: verified, branch-main, can-be-merged, size/S, approved-rnetser

#297 Fix aws cluster deletion on failure and osd creation when expiration -time is missing
  openshift_cli_installer/libs/clusters/aws_ipi_cluster.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
Labels: verified, branch-main, can-be-merged, size/S, approved-myakove, approved-calebevans, approved-chetna14manku

#305 Add command build script
  openshift_cli_installer/scripts/openshift-cli-installer-build-command.py
Labels: verified, branch-main, can-be-merged, size/m, approved-rnetser

#311 Fix command builder
  openshift_cli_installer/scripts/openshift-cli-installer-build-command.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-rnetser

#313 Add account roles to rosa install command to support HCP
  openshift_cli_installer/libs/clusters/rosa_cluster.py
Labels: verified, branch-main, can-be-merged, size/S, approved-myakove

#318 Remove kubeadmin-token extract and save
  openshift_cli_installer/libs/clusters/aws_ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, can-be-merged, size/m, approved-rnetser

#321 command-builder: fix parallel
  openshift_cli_installer/scripts/openshift-cli-installer-build-command.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-rnetser
