Repository RedHatQE/openshift-cli-installer, pull requests merged in 2023-10, with the labels that each got.

#205 Add option to collect must-gather
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/managed_clusters/acm_clusters.py
  openshift_cli_installer/libs/managed_clusters/osd_clusters.py
  openshift_cli_installer/libs/managed_clusters/rosa_clusters.py
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/manifests/clusters.example.yaml
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/const.py
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-myakove

#210 ACM: enabling-observability
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/managed_clusters/acm_clusters.py
  openshift_cli_installer/manifests/clusters.example.yaml
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/const.py
  poetry.lock
Labels: size/XXL, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#220 Report Total execution time
  openshift_cli_installer/cli.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-rnetser

#226 Save kubeadmin token to cluster_data.yaml
  openshift_cli_installer/cli.py
  openshift_cli_installer/utils/cli_utils.py
  poetry.lock
  pyproject.toml
Labels: verified, branch-main, size/XL, can-be-merged, ApprovedBy-rnetser

#230 save_kubeadmin_token_to_clusters_install_data: Use oc login
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-rnetser

#239 get_kubeadmin_token: pass `hide_log_command` to run_command
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-rnetser

#242 Change HOME dir for `oc login` only if running on openshift CI
  openshift_cli_installer/utils/cli_utils.py
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-rnetser

#249 get_kubeadmin_token: add `hide_log_command` option to oc command
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove, ApprovedBy-rnetser

#247 acm - add region to client
  openshift_cli_installer/libs/managed_clusters/acm_clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove

#253 cluster destroy: delete observability s3 bucket if exists
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/managed_clusters/acm_clusters.py
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/general.py
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-rnetser

#256 Move all user input related actions to `UserInput` class
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/tests/test_user_input.py
  openshift_cli_installer/utils/cli_utils.py
  tox.ini
Labels: size/XXL, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#258 Add `log-level` option for AWS IPI openshift-installer command
  README.md
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/manifests/clusters.example.yaml
Labels: verified, branch-main, can-be-merged, size/S, ApprovedBy-myakove

#260 Move all clusters code to classes
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/__init__.py
  openshift_cli_installer/libs/clusters/aws_ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocm_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/ocp_clusters.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/destroy_clusters.py
  openshift_cli_installer/libs/managed_clusters/acm_clusters.py
  openshift_cli_installer/libs/managed_clusters/helpers.py
  openshift_cli_installer/libs/managed_clusters/osd_clusters.py
  openshift_cli_installer/libs/managed_clusters/rosa_clusters.py
  openshift_cli_installer/libs/unmanaged_clusters/__init__.py
  openshift_cli_installer/libs/unmanaged_clusters/aws_ipi_clusters.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/tests/utils.py
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/gcp.py
  openshift_cli_installer/utils/general.py
  poetry.lock
  pyproject.toml
Labels: size/XXL, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#268 Fix destroy clusters from local dir and s3 bucket
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/utils/clusters.py
  openshift_cli_installer/utils/const.py
Labels: size/L, branch-main

#270 Support destroy clusters from s3 bucket using cluster_data.yaml
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, size/L, branch-main, can-be-merged, ApprovedBy-rnetser

#272 Add cluster_dir to cluster
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove

#274 Delete clusters (s3 or dir or yaml files) - fix code
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, branch-main, can-be-merged, ApprovedBy-myakove, size/m

#276 Update `USER_INPUT_CLUSTER_BOOLEAN_KEYS` constant
  openshift_cli_installer/utils/const.py
Labels: verified, branch-main, size/XS, can-be-merged, ApprovedBy-myakove
