Repository RedHatQE/openshift-cli-installer, pull requests merged in 2024-04, with the labels that each got.

#590 Update README
  README.md
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove, approved-chetna14manku

#592 Use `tts` from `pyhelper-utils`
  openshift_cli_installer/libs/clusters/ocm_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/utils/general.py
  poetry.lock
  pyproject.toml
Labels: verified, branch-main, can-be-merged, size/m, approved-rnetser

#598 hcp: add admin idp (user and password for login)
  README.md
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  poetry.lock
Labels: verified, size/L, branch-main, can-be-merged, approved-rnetser

#608 Update attirbutes paths, add region check and clusters-install-dir permissions
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/user_input.py
Labels: verified, branch-main, can-be-merged, size/S, approved-omrirh, approved-myakove, approved-chetna14manku, commented-rnetser

#610 Updating the pull image path in README file
  README.md
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove

#617 refactor find cluster version
  .pre-commit-config.yaml
  README.md
  openshift_cli_installer/libs/clusters/ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocm_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/tests/all_aws_versions.json
  openshift_cli_installer/tests/all_osd_versions.py
  openshift_cli_installer/tests/all_rosa_versions.py
  openshift_cli_installer/tests/cluster_version/__init__.py
  openshift_cli_installer/tests/cluster_version/aws_base_versions.py
  openshift_cli_installer/tests/cluster_version/constants.py
  openshift_cli_installer/tests/cluster_version/rosa_osd_base_versions.py
  openshift_cli_installer/tests/cluster_version/test_aws_version.py
  openshift_cli_installer/tests/cluster_version/test_osd_rosa_versions.py
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/tests/test_user_input.py
  openshift_cli_installer/tests/utils.py
  openshift_cli_installer/utils/cluster_versions.py
  pyproject.toml
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser

#619 User input tests refactor
  openshift_cli_installer/cli.py
  openshift_cli_installer/cli_entrypoint.py
  openshift_cli_installer/libs/clusters/ocm_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/tests/test_user_input.py
  openshift_cli_installer/utils/cli_utils.py
  openshift_cli_installer/utils/cluster_versions.py
  pyproject.toml
  tox.ini
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser

#627 add pyhelper-utils to renovate
  renovate.json
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove
