Repository RedHatQE/openshift-cli-installer, pull requests merged in 2024-03, with the labels that each got.

#530 [LPTOCPCI-1173] Use new "get_roles" function in cloud-tools
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  poetry.lock
  pyproject.toml
Labels: verified, branch-main, size/XL, can-be-merged, approved-myakove

#553 Refactor: Use `UserInput` object
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocm_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/ocp_clusters.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/utils/clusters.py
Labels: verified, size/L, branch-main, can-be-merged, approved-rnetser

#565 Exclude user_input from cluster config file
  openshift_cli_installer/libs/clusters/ocp_cluster.py
Labels: verified, branch-main, size/XS, needs-rebase

#556 Add tests for `UserInput` class
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/tests/test_user_input.py
  poetry.lock
  pyproject.toml
  pytest.ini
  scripts/code_check/__init__.py
  scripts/code_check/unused_code.py
  tox.ini
Labels: verified, branch-main, size/XL, can-be-merged, approved-rnetser, commented-myakove

#568 move attrbutes in ocp cluster
  openshift_cli_installer/libs/clusters/ocp_cluster.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove

#573 Use user_input for must-gather-output-dir
  openshift_cli_installer/libs/clusters/ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-rnetser

#579 dockerfile: clean apt files
  Dockerfile
Labels: verified, branch-main, size/XS, can-be-merged, approved-rnetser
