Repository RedHatQE/openshift-cli-installer, pull requests merged in 2024-02, with the labels that each got.

#422 Support cluster name prefix
  README.md
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/manifests/clusters.example.yaml
Labels: verified, branch-main, can-be-merged, size/S, approved-rnetser, approved-chetna14manku

#424 Fix cluster name prefix, set lower case
  openshift_cli_installer/libs/clusters/ocp_cluster.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-rnetser

#426 OSD - check gpc file only for gcp cluster
  openshift_cli_installer/libs/clusters/osd_cluster.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove

#439 Get S3 bucket object name from user
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/scripts/openshift-cli-installer-build-command.py
  openshift_cli_installer/utils/general.py
Labels: verified, branch-main, can-be-merged, size/S, approved-myakove

#441 Fix poetry script and rename it
  pyproject.toml
Labels: verified, branch-main, size/XS, can-be-merged, approved-rnetser, approved-chetna14manku

#443 use wolrus operator in script
  openshift_cli_installer/scripts/openshift-cli-installer-build-command.py
Labels: verified, branch-main, can-be-merged, size/m, approved-myakove

#445 pass log to ignore_exceptions
  openshift_cli_installer/utils/general.py
Labels: branch-main, size/XS

#449 update zip filepath
  openshift_cli_installer/utils/general.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove

#468 Add function to check if OCP version is accepted
  .flake8
  openshift_cli_installer/utils/cluster_versions.py
  poetry.lock
  pyproject.toml
Labels: verified, branch-main, can-be-merged, size/m, approved-rnetser

#471 IPI clusters: Get only accepted versions
  .flake8
  openshift_cli_installer/libs/clusters/ipi_cluster.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/tests/all_aws_versions.json
  openshift_cli_installer/tests/test_cluster_version.py
  openshift_cli_installer/utils/cluster_versions.py
Labels: verified, size/L, branch-main, can-be-merged, approved-rnetser

#485 remove command builder script
  openshift_cli_installer/scripts/openshift-cli-installer-build-command.py
  openshift_cli_installer/tests/test_build_command_script.py
Labels: verified, branch-main, can-be-merged, size/m, approved-myakove
