Repository RedHatQE/openshift-cli-installer, pull requests merged in 2024-01, with the labels that each got.

#347 User timeout-sampler module
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  poetry.lock
  pyproject.toml
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove

#352 update github solidarity config for IPI manifests path
  .github/in-solidarity.yml
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove

#355 Fix Inclusive Language ignore role
  .github/in-solidarity.yml
Labels: verified, branch-main, size/XS

#332 Add GCP IPI support
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/ipi_cluster.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/ocp_clusters.py
  openshift_cli_installer/libs/clusters/osd_cluster.py
  openshift_cli_installer/libs/user_input.py
  openshift_cli_installer/manifests/aws-install-config-template.j2
  openshift_cli_installer/manifests/clusters.example.yaml
  openshift_cli_installer/manifests/gcp-install-config-template.j2
  openshift_cli_installer/tests/utils.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/const.py
  openshift_cli_installer/utils/gcp_utils.py
  openshift_cli_installer/utils/general.py
Labels: verified, branch-main, size/XL, can-be-merged, approved-myakove, commented-chetna14manku

#390 Add gcp to ROSA command ignore prefixes
  openshift_cli_installer/libs/clusters/ipi_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/libs/user_input.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove

#394 Use logger instead of `click.echo` or `click.secho`
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/ocp_clusters.py
  openshift_cli_installer/utils/cluster_versions.py
  openshift_cli_installer/utils/const.py
  openshift_cli_installer/utils/general.py
Labels: verified, branch-main, can-be-merged, size/S, approved-myakove

#386 Select auto-region for AWS cluster
  README.md
  openshift_cli_installer/cli.py
  openshift_cli_installer/libs/clusters/ocp_cluster.py
  openshift_cli_installer/libs/clusters/rosa_cluster.py
  openshift_cli_installer/manifests/clusters.example.yaml
  openshift_cli_installer/utils/const.py
Labels: verified, branch-main, can-be-merged, size/m, approved-myakove
